name: Terraform Deployment

on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0 # specify the version of Terraform you need

      - name: Terraform Init
        run: terraform init
        working-directory: /.github-workflows

      - name: Terraform Plan
        run: terraform plan
        working-directory: /.github-workflows

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: /.github-workflows
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
